[package]
name = "nim_game"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
weighted-rs = "0.1.3"
fxhash = "0.2.1"
derive_more = "0.99.17"